troiswa_test_homepage:
    pattern: /
    defaults: { _controller: "TroiswaTestBundle:Main:index" }

troiswa_test_image:
    resource: "@TroiswaTestBundle/Resources/config/routing/image.yml"
    prefix:   /image

TroiswaTestBundle_actor:
        resource: "@TroiswaTestBundle/Resources/config/routing/actor.yml"
        prefix:   /actor

TroiswaTestBundle_movie:
        resource: "@TroiswaTestBundle/Resources/config/routing/movie.yml"
        prefix:   /movie

TroiswaTestBundle_category:
        resource: "@TroiswaTestBundle/Resources/config/routing/category.yml"
        prefix:   /category

TroiswaTestBundle_tag:
        resource: "@TroiswaTestBundle/Resources/config/routing/tag.yml"
        prefix:   /tag

TroiswaTestBundle_seance:
        resource: "@TroiswaTestBundle/Resources/config/routing/seance.yml"
        prefix:   /seance

TroiswaTestBundle_cinema:
        resource: "@TroiswaTestBundle/Resources/config/routing/cinema.yml"
        prefix:   /cinema