parameters:
#    troiswa_test.example.class: Troiswa\TestBundle\Example

services:
#    troiswa_test.example:
#        class: %troiswa_test.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
        troiswa_test.twig.util_extension:
            class: Troiswa\TestBundle\Twig\UtilExtension
            tags:
                - { name: twig.extension }

        twig.extension.intl:
            class: Twig_Extensions_Extension_Intl
            tags:
                - { name: twig.extension }

        troiswa_public.email:
            class: Troiswa\TestBundle\EmailDecorator\Email
            arguments: [@templating, @mailer]