<?php

namespace Troiswa\TestBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CinemaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CinemaRepository extends EntityRepository
{
	public function findFilm($id_cinema)
	{
		$req = $this->_em->createQuery(
			'SELECT m
			FROM TroiswaTestBundle:Movie m
			JOIN TroiswaTestBundle:Seance s WITH s.movie = m
			WHERE s.cinema = :id_cinema
			'
			)
		->setParameter('id_cinema', $id_cinema);

		return $req->getResult();
	}
}
