<?php

namespace Troiswa\TestBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MovieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovieRepository extends EntityRepository
{
	public function search($word){
        $query = $this->_em
            ->createQuery(
                'SELECT m
                FROM TroiswaTestBundle:Movie m
                WHERE m.titre LIKE :movie'
            )
            ->setParameter('movie', "%".$word."%");

            return $query->getResult();
    }
}
